add end of line

diff --git a/clusters/cl01tl/platform/qbittorrent/templates/config-map.yaml b/clusters/cl01tl/platform/qbittorrent/templates/config-map.yaml
--- a/clusters/cl01tl/platform/qbittorrent/templates/config-map.yaml
+++ b/clusters/cl01tl/platform/qbittorrent/templates/config-map.yaml
@@ -11,10 +11,10 @@ metadata:
     app.kubernetes.io/part-of: {{ .Release.Name }}
 data:
   update.sh: |
-    if ! command -v curl 2>&1 >/dev/null
-    then
-        echo "curl could not be found, installing"
-        apk add curl
-    fi
-    echo "updating port with $1"
-    curl -i -X POST -d "json={\"listen_port\": \"${1}\"}" "http://localhost:8080/api/v2/app/setPreferences"
+  if ! command -v curl 2>&1 >/dev/null
+  then
+      echo "curl could not be found, installing";
+      apk add curl;
+  fi;
+  echo "updating port with $1";
+  curl -i -X POST -d "json={\"listen_port\": \"${1}\"}" "http://localhost:8080/api/v2/app/setPreferences";
