feat: add dir output to render

diff --git a/.gitea/workflows/render-manifests.yaml b/.gitea/workflows/render-manifests.yaml
--- a/.gitea/workflows/render-manifests.yaml
+++ b/.gitea/workflows/render-manifests.yaml
@@ -49,7 +49,7 @@ jobs:
           ref: manifests
           path: infrastructure-manifests
 
-      - name: Set up Helm
+      - name: Set Up Helm
         uses: azure/setup-helm@v4
         with:
           token: ${{ secrets.GITEA_TOKEN }}
@@ -150,7 +150,7 @@ jobs:
 
           echo "BRANCH_NAME=${BRANCH_NAME}" >> "$GITHUB_OUTPUT"
 
-      - name: Check which Directories have Changes
+      - name: Check Which Directories Have Changes
         id: check-dir-changes
         env:
           RENDER_ALL: ${{ steps.mode.outputs.render_all }}
@@ -174,6 +174,7 @@ jobs:
             echo ""
             echo "${RENDER_DIR}"
 
+            echo ""
             echo "----"
 
             echo "changes-detected=true" >> "$GITHUB_OUTPUT"
@@ -237,6 +238,7 @@ jobs:
           cd "${MANIFEST_DIR}"
 
           echo ">> Remove manifest files and rebuild from source ..."
+          echo ""
 
           for DIR in ${RENDER_DIR}; do
             CHART_PATH="${MANIFEST_DIR}/clusters/${CLUSTER}/manifests/${DIR}"
@@ -280,20 +282,16 @@ jobs:
               case "${CHART_NAME}" in
                 "stack")
                   NAMESPACE="argocd"
-                  echo ""
                   echo ">> Special Rendering into 'argocd' namespace ..."
                   ;;
                 "cilium" | "coredns" | "metrics-server" | "prometheus-operator-crds")
                   NAMESPACE="kube-system"
-                  echo ""
                   echo ">> Special Rendering for ${CHART_NAME} into 'kube-system' namespace ..."
                   ;;
                 *)
-                  echo ""
-                  echo ">> Standard Rendering for ${CHART_NAME} ..."
+                  echo ">> Standard Rendering ..."
               esac
 
-              echo ""
               echo ">> Formating rendered template ..."
               local TEMPLATE
               TEMPLATE=$(helm template "${CHART_NAME}" ./ --namespace "${NAMESPACE}" --include-crds --dry-run=server --api-versions "gateway.networking.k8s.io/v1/HTTPRoute")
@@ -307,8 +305,10 @@ jobs:
 
               done
 
+              echo ">> Manifests for ${CHART_NAME} rendered successfully to $OUTPUT_FOLDER:"
               echo ""
-              echo ">> Manifests for ${CHART_NAME} rendered successfully."
+              ls $OUTPUT_FOLDER
+              echo ""
 
             else
               echo ""
@@ -480,10 +480,12 @@ jobs:
 
           else
             echo ""
-            echo ">> Failed to create PR, HTTP status code: $HTTP_STATUS"; exit 1
+            echo ">> Failed to create PR, HTTP status code: $HTTP_STATUS"
 
             echo ""
             echo "----"
+
+            exit 1
 
           fi
 
