chore: Update manifests after change

diff --git a/clusters/cl01tl/manifests/talos/ConfigMap-talos-prune-script.yaml b/clusters/cl01tl/manifests/talos/ConfigMap-talos-prune-script.yaml
--- a/clusters/cl01tl/manifests/talos/ConfigMap-talos-prune-script.yaml
+++ b/clusters/cl01tl/manifests/talos/ConfigMap-talos-prune-script.yaml
@@ -8,142 +8,4 @@ metadata:
     app.kubernetes.io/instance: talos
     app.kubernetes.io/part-of: talos
 data:
-  prune.sh: |
-    DATE_RANGE=$(date -d @$(( $(date +%s) - $DATE_RANGE_SECONDS )) +%Y-%m-%dT%H:%M:%SZ);
-    FILE_MATCH="${BUCKET}/cl01tl/etcd/cl01tl-${DATE_RANGE}.snap.age";
-    ERROR=false;
-    MESSAGE="";
-
-    echo "";
-    echo ">> Running S3 prune for Talos backup repository ${TARGET} ...";
-
-    echo "";
-    echo ">> Configured Date Range is $(date -u -d @${DATE_RANGE_SECONDS} +"%j days, %H hours, %M minutes")";
-    echo ">> Backups prior to '$DATE_RANGE' will be removed";
-    echo "";
-
-    FILES=$(s3cmd ls --no-check-certificate "${BUCKET}/cl01tl/etcd/" | \
-        awk -v file_match="$FILE_MATCH" '$4 < file_match && $4 !~ /\/$/ {print $4}')
-
-    if [ $? -ne 0 ]; then
-        echo "";
-        echo ">> Detected error, will send message to ntfy";
-
-        ERROR=true;
-        MESSAGE="Error collecting files to delete from '${TARGET}'";
-
-    elif [ -n "${FILES}" ]; then
-        echo "";
-        echo ">> Backups to be removed:";
-        echo "";
-        echo "$FILES";
-        echo "";
-        echo ">> Deleting ...";
-
-        for file in $FILES; do
-            s3cmd del --no-check-certificate -v "${file}";
-
-            if [ $? -ne 0 ]; then
-                echo ">> Detected error, will send message to ntfy";
-
-                ERROR=true;
-                MESSAGE="Error deleting file from '${TARGET}'";
-
-            fi;
-        done;
-
-    else
-        echo "";
-        echo ">> No backups to remove";
-
-        exit 0;
-
-    fi;
-
-    MAX_RETRIES=5;
-    SUCCESS=false;
-
-    echo "";
-    echo ">> Sending message to ntfy using curl ...";
-
-    echo "";
-    echo ">> Verifying required commands ...";
-
-    for i in $(seq 1 "$MAX_RETRIES"); do
-        if apk update >/dev/null 2>&1; then
-            echo ">> Attempt $i: Repositories are reachable";
-
-            SUCCESS=true;
-
-            break;
-
-        else
-            echo ">> Attempt $i: Connection failed, retrying in 5 seconds ...";
-
-            sleep 5;
-
-        fi;
-    done;
-
-    if [ "$SUCCESS" = false ]; then
-        echo ">> ERROR: Could not connect to apk repositories after $MAX_RETRIES attempts, exiting ...";
-
-        exit 1;
-
-    fi
-
-    if ! command -v curl >/dev/null 2>&1; then
-        echo ">> Command curl could not be found, installing";
-
-        apk add --no-cache -q curl;
-
-        if [ $? -eq 0 ]; then
-            echo ">> Installation successful";
-
-        else
-            echo ">> Installation failed with exit code $?";
-
-            exit 1;
-
-        fi;
-    fi;
-
-    echo "";
-    echo ">> Sending to NTFY ...";
-
-    if [ "$ERROR" = "true" ]; then
-        HTTP_STATUS=$(curl \
-            --silent \
-            --write-out '%{http_code}' \
-            -H "Authorization: Bearer ${NTFY_TOKEN}" \
-            -H "X-Priority: 5" \
-            -H "X-Tags: warning" \
-            -H "X-Title: Talos Backup Prune Failed for ${TARGET}" \
-            -d "$MESSAGE" \
-            ${NTFY_ENDPOINT}/${NTFY_TOPIC}
-        );
-
-        echo ">> HTTP Status Code: $HTTP_STATUS";
-
-        exit 1;
-
-    else
-        MESSAGE="Pruned $(echo "$FILES" | wc -l) files"
-
-        HTTP_STATUS=$(curl \
-            --silent \
-            --write-out '%{http_code}' \
-            -H "Authorization: Bearer ${NTFY_TOKEN}" \
-            -H "X-Priority: 3" \
-            -H "X-Tags: completed" \
-            -H "X-Title: Talos Backup Prune Success for ${TARGET}" \
-            -d "$MESSAGE" \
-            ${NTFY_ENDPOINT}/${NTFY_TOPIC}
-        );
-
-        echo ">> HTTP Status Code: $HTTP_STATUS";
-
-    fi;
-
-    echo "";
-    echo ">> Completed S3 prune for Talos backup repository ${TARGET}";
+  prune.sh: "DATE_RANGE=$(date -d @$(( $(date +%s) - $DATE_RANGE_SECONDS )) +%Y-%m-%dT%H:%M:%SZ);\nFILE_MATCH=\"${BUCKET}/cl01tl/etcd/cl01tl-${DATE_RANGE}.snap.age\";\nERROR=false;\nMESSAGE=\"\";\n\necho \"\";\necho \">> Running S3 prune for Talos backup repository ${TARGET} ...\";\n\necho \"\";\necho \">> Configured Date Range is $(date -u -d @${DATE_RANGE_SECONDS} +\"%j days, %H hours, %M minutes\")\";\necho \">> Backups prior to '$DATE_RANGE' will be removed\";\necho \"\";\n\nFILES=$(s3cmd ls --no-check-certificate \"${BUCKET}/cl01tl/etcd/\" | \\\n    awk -v file_match=\"$FILE_MATCH\" '$4 < file_match && $4 !~ /\\/$/ {print $4}')\n\nif [ $? -ne 0 ]; then\n    echo \"\";\n    echo \">> Detected error, will send message to ntfy\";\n\n    ERROR=true;\n    MESSAGE=\"Error collecting files to delete from '${TARGET}'\";\n\nelif [ -n \"${FILES}\" ]; then\n    echo \"\";\n    echo \">> Backups to be removed:\";\n    echo \"\";\n    echo \"$FILES\";\n    echo \"\";\n    echo \">> Deleting ...\";\n\n    for file in $FILES; do\n        s3cmd del --no-check-certificate -v \"${file}\";\n\n        if [ $? -ne 0 ]; then\n            echo \">> Detected error, will send message to ntfy\";\n            ERROR=true;\n            MESSAGE=\"Error deleting file from '${TARGET}'\";\n\n        else\n            PRUNED_COUNT=$((PRUNED_COUNT + 1));\n\n        fi;\n    done;\n\nelse\n    echo \"\";\n    echo \">> No backups to remove\";\n\nfi;\n\necho \"\";\necho \">> Calculating total objects in repository ...\";\nTOTAL_OBJECTS=$(s3cmd ls --no-check-certificate \"${BUCKET}/cl01tl/etcd/\" | \\\n    awk '$4 !~ /\\/$/ {count++} END {print count+0}');\n\necho \">> Total objects in ${BUCKET}/cl01tl/etcd/: ${TOTAL_OBJECTS}\";\n\nMAX_RETRIES=5;\nSUCCESS=false;\n\necho \"\";\necho \">> Sending message to ntfy using curl ...\";\n\necho \"\";\necho \">> Verifying required commands ...\";\n\nfor i in $(seq 1 \"$MAX_RETRIES\"); do\n    if apk update >/dev/null 2>&1; then\n        echo \">> Attempt $i: Repositories are reachable\";\n        SUCCESS=true;\n        break;\n\n    else\n        echo \">> Attempt $i: Connection failed, retrying in 5 seconds ...\";\n        sleep 5;\n\n    fi;\ndone;\n\nif [ \"$SUCCESS\" = false ]; then\n    echo \">> ERROR: Could not connect to apk repositories after $MAX_RETRIES attempts, exiting ...\";\n    exit 1;\n\nfi\n\nif ! command -v curl >/dev/null 2>&1; then\n    echo \">> Command curl could not be found, installing\";\n    apk add --no-cache -q curl;\n    if [ $? -eq 0 ]; then\n        echo \">> Installation successful\";\n\n    else\n        echo \">> Installation failed with exit code $?\";\n        exit 1;\n\n    fi;\nfi;\n\necho \"\";\necho \">> Sending to NTFY ...\";\n\nif [ \"$ERROR\" = \"true\" ]; then\n    HTTP_STATUS=$(curl \\\n        --silent \\\n        --write-out '%{http_code}' \\\n        -H \"Authorization: Bearer ${NTFY_TOKEN}\" \\\n        -H \"X-Priority: 5\" \\\n        -H \"X-Tags: warning\" \\\n        -H \"X-Title: \U0001F6A8 Talos Backup Prune Failed for ${TARGET}\" \\\n        -d \"$MESSAGE\" \\\n        ${NTFY_ENDPOINT}/${NTFY_TOPIC}\n    );\n    echo \">> HTTP Status Code: $HTTP_STATUS\";\n    exit 1;\n\nelse\n    MESSAGE=\"Pruned ${PRUNED_COUNT} files, now ${TOTAL_OBJECTS} objects in bucket\";\n    HTTP_STATUS=$(curl \\\n        --silent \\\n        --write-out '%{http_code}' \\\n        -H \"Authorization: Bearer ${NTFY_TOKEN}\" \\\n        -H \"X-Priority: 3\" \\\n        -H \"X-Tags: completed\" \\\n        -H \"X-Title: ✅ Talos Backup Prune Success for ${TARGET}\" \\\n        -d \"$MESSAGE\" \\\n        ${NTFY_ENDPOINT}/${NTFY_TOPIC}\n    );\n    echo \">> HTTP Status Code: $HTTP_STATUS\";\n\nfi;\n\necho \"\";\necho \">> Completed S3 prune for Talos backup repository ${TARGET}\";\n"
