Automated Manifest Update (#2743)
This PR contains newly rendered Kubernetes manifests automatically generated by the CI workflow.

Reviewed-on: https://gitea.alexlebens.dev/alexlebens/infrastructure/pulls/2743
Co-authored-by: gitea-bot <gitea-bot@alexlebens.net>
Co-committed-by: gitea-bot <gitea-bot@alexlebens.net>

diff --git a/clusters/cl01tl/manifests/qbittorrent/ConfigMap-glutun-update-script.yaml b/clusters/cl01tl/manifests/qbittorrent/ConfigMap-glutun-update-script.yaml
--- a/clusters/cl01tl/manifests/qbittorrent/ConfigMap-glutun-update-script.yaml
+++ b/clusters/cl01tl/manifests/qbittorrent/ConfigMap-glutun-update-script.yaml
@@ -9,19 +9,49 @@ metadata:
     app.kubernetes.io/part-of: qbittorrent
 data:
   update.sh: |
+    API_ENDPOINT="http://localhost:8080/api/v2";
+    MAX_RETRIES=5
+    SUCCESS=false
+
+    for ((i=1; i<=$MAX_RETRIES; i++)); do
+        if apk update --short &> /dev/null; then
+            echo ">> Attempt $i: Repositories are reachable"
+            SUCCESS=true
+            break
+        else
+            echo ">> Attempt $i: Connection failed, retrying in 5 seconds ..."
+            sleep 5
+        fi
+    done
+
+    if [ "$SUCCESS" = false ]; then
+        echo ">> ERROR: Could not connect to apk repositories after $MAX_RETRIES attempts, exiting ..."
+        exit 1
+    fi
+
     if ! command -v curl 2>&1 >/dev/null
     then
         echo "curl could not be found, installing";
-        apk add curl;
+        apk add --no-cache curl;
+        if [ $? -eq 0 ]; then
+            echo ">> Installation successful"
+        else
+            echo ">> Installation failed with exit code $?"
+            exit 1
+        fi
     fi;
 
     if ! command -v jq 2>&1 >/dev/null
     then
         echo "jq could not be found, installing";
-        apk add jq;
+        apk add --no-cache jq;
+        if [ $? -eq 0 ]; then
+            echo ">> Installation successful"
+        else
+            echo ">> Installation failed with exit code $?"
+            exit 1
+        fi
     fi;
-
-    API_ENDPOINT="http://localhost:8080/api/v2";
 
     # echo " ";
     # echo ">> Authentication ...";
